### ISSUE TITLE
Assinatura

### ISSUE THREAD

**Issue by Bonfante** [moip/moip-sdk-php#102]
o sdk php moip não lida com assinatura?
tentei achar como gerar assinatura mas não encontrei nada

**Comment by marcos150895** [comment]
@Bonfante o moip não tem um sdk-php para o assinaturas,

Nesse caso você teria que desenvolver por sua parte essa integração.

**Comment by SOSTheBlack** [comment]
@Bonfante é isso ai que o @marcos150895  disse.
O sdk não cobriu 100% a API do MoIP.
Se quiser contribuir você mesmo pode desenvolver essa parte do sdk, basta subir para o branch dev seu pr.

Abraços.

**Comment by Bonfante** [comment]
Ok, verei como farei. 
Obrigado
