### ISSUE TITLE
Moip\Exceptions\Error::parseErrors() returns no message if a requested resource is not found

### ISSUE THREAD

**Issue by dmitry-fedyuk** [moip/moip-sdk-php#104]
The `Moip\Exceptions\Error::parseErrors()` method is implemented as:

```
public static function parseErrors($json_string)
{
	$error_obj = json_decode($json_string);
	$errors = [];
	if (!empty($error_obj->errors)) {
		foreach ($error_obj->errors as $error) {
			$errors[] = new self($error->code, $error->path, $error->description);
		}
	}

	return $errors;
}
```
https://github.com/moip/moip-sdk-php/blob/v1.1.2/src/Exceptions/Error.php#L89-L93

But if a requested resource (e.g., customer) is not found, then Moip returns the response:
```
{"error":"resource not found"}
```

The `Moip\Exceptions\Error::parseErrors()` method does not correctly handle this message ("`resource not found`") because it looks only for `!empty($error_obj->errors)`, and creates an exception without any message.

**Comment by SOSTheBlack** [comment]
This was resolved in version v1.2
