### ISSUE TITLE
The «POST /v2/customers/customer_id/fundinginstruments» API operation is not implemented in the SDK

### ISSUE THREAD

**Issue by dmitry-fedyuk** [moip/moip-sdk-php#105]
https://dev.moip.com.br/v2.0/reference#adicionar-cartao-de-credito

**Comment by SOSTheBlack** [comment]
https://github.com/moip/moip-sdk-php/projects/2#card-3184305

**Comment by SOSTheBlack** [comment]
https://github.com/moip/moip-sdk-php/blob/master/src/Resource/CustomerCreditCard.php

**Comment by erickne** [comment]
@SOSTheBlack atualize a tag de versão para incluir esse arquivo. A documentação fica defasada sem ele.
