### ISSUE TITLE
Recuperar Link do Payment.

### ISSUE THREAD

**Issue by jhernandes** [moip/moip-sdk-php#126]
Na versão 1.1 era possível recuperar o Link:

$payment->getLinks()->getLink('payBoleto')->getHref();

Na versão 1.2 não encontrei uma forma direta para recuperar este mesmo link.

$payment->getLinks()->getCheckout($pay) não funciona da forma esperada. (Retorna sempre null).

O link em Helpers/Links.php pode ser recuperado da seguinte forma:

$this->links->$pay->redirectHref;

**Comment by prhost** [comment]
alguma previsão pra solução deste problema?

**Comment by caiogaspar** [comment]
@jhernandes e @prhost, tudo certo? 
Estou no time aqui do @moip que cuida das SDKs e fizemos um pull request para corrigir e conseguir recuperar esse link do payment. 
Estamos trabalhando em uma nova versão da SDK, adicionando novas features e outras coisas bacanas pra melhorar ainda mais o projeto.
Enquanto não lançamos a nova versão, usando a versão **```dev-master```** você pode recuperar o link dessa forma: $payment->getLinks()->getLink('payBoleto'). 

Abs,
Caio Gaspar

**Comment by prhost** [comment]
@caiogaspar valeu

**Comment by lucassena** [comment]
@caiogaspar não é meio perigoso usar o dev-master?

**Comment by caiogaspar** [comment]
@lucassena Estamos bem próximos de lançar uma nova versão estável para evitar o uso da dev-master, essa é uma solução estritamente temporária.

**Comment by lucassena** [comment]
@caiogaspar Ok, vou usar dev-master então, mas vou ver se fico bem atento quando tiver alguma mudança pra não dar problemas no pagamento na minha plataforma.

Obrigado Caio,

**Comment by lucassena** [comment]
@caiogaspar Cara, tem alguma forma de eu saber um momento antes de vocês atualizarem o master com essa nova versão?

Nem que seja por Whatsapp, qlqr coisa, hehe...

Abs

**Comment by caiogaspar** [comment]
@lucassena Olá Lucas, infelizmente nós não temos como avisar todo mundo antes de lançar, porém entendo sua preocupação. Uma solução seria passar o hash do commit para o dev-master no composer.json, como fizeram aqui https://stackoverflow.com/questions/21314381/how-to-correctly-require-a-specific-commit-in-composer-so-that-it-would-be-avail.
Abs,
Caio Gaspar

**Comment by lucassena** [comment]
Valeu, @caiogaspar!! Vou fazer isso!

**Comment by prhost** [comment]
@caiogaspar meu problema é um pouco mais complicado, tive que duplicar o repositório e fechar uma tag pra mim porque eu uso o package dentro de outro package, o composer não permite versões dev com stable, se eu permitir `minimum-stability` pra dev ai todos os meus pacotes vão baixar versão de dev não so o SDK. Não sei se deu pra entender kk, então eu preciso do quanto antes essa nova versão, ou vou continuar usando o meu repositório.

@lucassena Você pode assinar para receber notificação do repositório no botão watch. fica a dica.
