### ISSUE TITLE
Duplicate Reource\Payment

### ISSUE THREAD

**Issue by SOSTheBlack** [moip/moip-sdk-php#142]
@caiogaspar 
 a Classe `Moip\Resource\Payment` está duplicada no projeto.

A pasta correta é está:
[(R)eource](https://github.com/moip/moip-sdk-php/tree/master/src/Resource
)
E você criou essa:
[(r)esource](https://github.com/moip/moip-sdk-php/tree/master/src/resource
)
A class `Payment` são iguais em ambas, é necessário que a pasta [resource](https://github.com/moip/moip-sdk-php/tree/master/src/resource) que você criou seja exclusa

Descobri por que o [software de integração](https://scrutinizer-ci.com/g/moip/moip-sdk-php/inspections/f328662f-df04-4237-b0fc-512f9b6004b0/code-structure/class/Moip%5CResource%5CPayment) continua acusou a duplicidade.

**Comment by caiogaspar** [comment]
@SOSTheBlack Obrigado por avisar, o erro foi ocasionado por causa do case-sensitive do sistema operacional. Já foi deletado!

**Comment by SOSTheBlack** [comment]
Shooow!
