### ISSUE TITLE
$moip->notifications() não tem na ultima versão disponivel v1.2.0

### ISSUE THREAD

**Issue by prhost** [moip/moip-sdk-php#143]
https://github.com/moip/moip-sdk-php/wiki/Criar-prefer%C3%AAncia-de-notifica%C3%A7%C3%A3o

Tem alguma previsão de lançamento da próxima versão? 
Estou desenvolvendo com a versão `dev-master` enquanto não sai a versão estável com esta funcionalidade.

**Comment by joaolucasl** [comment]
Oi @prhost! Acabamos de lançar a [v1.3.0](https://packagist.org/packages/moip/moip-sdk-php#v1.3.0)!
Desculpe pela demora, estamos arrumando a casa ainda :)

Abraço!

**Comment by prhost** [comment]
ja atualizei aqui (:
obrigado
