### ISSUE TITLE
getIfSetDateTime() está incorreto?

### ISSUE THREAD

**Issue by lucassena** [moip/moip-sdk-php#147]
No objeto **moip-sdk-php/src/Resource/MoipResource.php** o método `getIfSetDateTime()` e outros métodos semelhantes me parecem estar incorretos.

Alguém está usando isso? Posso mandar um PR com a correção. Mas enquanto isso estou usando o `getIfSet()` no método _Event->getCreatedAt()_.

Abs,

**Comment by caiogaspar** [comment]
Resolvido em #152
