### ISSUE TITLE
Débito em conta

### ISSUE THREAD

**Issue by czmarcos** [moip/moip-sdk-php#160]
A api suporta pagamentos via débito em conta? Se suportar, sabem quais bancos são aceitos?
Na documentação da api vi que há a opção de ONLINE_BANK_DEBIT, mas não encontrei instruções aqui na api do php.

**Comment by caiogaspar** [comment]
@czmarcos Olá Marcos, tudo bem? É possível fazer pagamentos via débito online usando a SDK, você pode ver um exemplo nesse link https://documentao-moip.readme.io/v2.0/reference#criar-pagamento. Atualmente o único banco aceito é o Itaú.
Abs,
Caio Gaspar
