### ISSUE TITLE
Retornar ID de contas MOIP

### ISSUE THREAD

**Issue by raulfdias** [moip/moip-sdk-php#161]
Boa tarde. Exite alguma maneira de retornar o ID de uma conta MOIP para utilizar no SPLIT PAYMENT?
Estou até o momento tentando buscar esta informação utilizando os serviços existentes mas sem sucesso. Acredito que possa ser verificado um parâmetro para ser utilizado para trazer os dados de uma conta ao invés do próprio ID, até por uma necessidade como acontece neste caso.
A única maneira que encontrei foi acessando a conta do cliente indo em editar perfil e copiando da URL.

**Comment by caiogaspar** [comment]
Olá Raul,
Nesse caso você pode receber as informações da conta pelo Moip Connect (permissão de terceiros), ou ao tentar criar uma conta Moip pela API se o CPF e email da pessoa já estiverem cadastrados a própria API retornará status code 400 e passará o ID da conta.
Abs,
Caio Gaspar

**Comment by fernandoofj** [comment]
Olá @caiogaspar tudo joia?
Tentei criar uma conta existente [sandbox] para pegar o ID dela, porem a unica coisa retornada foi...

accessToken 
94c27d0239e24569ba645ccebfaee200_v2

gatewayMode 
sandbox

Exception 
Moip\Exceptions\ValidationException Object
(
    [statusCode:Moip\Exceptions\ValidationException:private] => 400
    [errors:Moip\Exceptions\ValidationException:private] => Array
        (
            [0] => Moip\Exceptions\Error Object
                (
                    [code:Moip\Exceptions\Error:private] => REG-408
                    [path:Moip\Exceptions\Error:private] => person[taxDocument][number]
                    [description:Moip\Exceptions\Error:private] => Has already been taken
                )

        )
