### ISSUE TITLE
Criar método que lista as preferências de notificações.

### ISSUE THREAD

**Issue by lucascolette** [moip/moip-sdk-php#170]
Hoje só temos disponíveis os métodos:

get(notification_id), delete() e create() na classe Moip\Resource\NotificationPreferences;

Seria interessante algum método getAll() que retorna todas as preferências de notificações relacionadas no endpoint: https://...moip.com.br/v2/preferences/notifications

**Comment by caiogaspar** [comment]
Olá @lucascolette, essa feature já está sendo criada e estará disponível no próximo release.
Fique ligado no nosso repositório, em breve teremos mais novidades!
Abs,
Caio Gaspar
