### ISSUE TITLE
Não é possível acessar _links em orders?

### ISSUE THREAD

**Issue by dyegonery** [moip/moip-sdk-php#178]
Após criar um order, não consegui encontrar um método para ser utilizado no caso de eu querer utilizar o webcheckout do próprio Moip. Alguém pode me indicar um método para buscar os links após a criação do pedido, por favor?

**Comment by caiogaspar** [comment]
Olá @dyegonery, tudo bem?
É possível pegar os links de order dessa forma:
```php
$order_created->getLinks()->getLink('link-desejado');
```
O `'link-desejado'` é só um exemplo, você deve trocar ele por `self`, `checkout` ou qualquer outro link que você deseja acessar.

Abs,
Caio Gaspar
