### ISSUE TITLE
[BANKING] Add Bank Accounts

### ISSUE THREAD

**Issue by joaolucasl** [moip/moip-sdk-php#185]
The following features should be added to support Bank Accounts:
 - [ ] Create a specific Bank Account
 - [ ] Update a specific Bank Account
 - [ ] Delete a specific Bank Account
 - [ ] Show a specific Bank Account
 - [ ] List All Bank Accounts

You can find the official documentation [here](https://documentao-moip.readme.io/v2.0/reference#contas-bancárias)!

<hr/>

### Implementation Tips:
You can draw inspiration from [this PR](https://github.com/moip/moip-sdk-php/pull/181/files). Don't forget to write good tests, and to document it on our `README`

**Comment by ecordoba24** [comment]
Hi Joao please confirm that these issues has been completed 
https://documentao-moip.readme.io/v2.0/reference#criar-conta-banc%C3%A1ria

**Comment by joaolucasl** [comment]
Hi @ecordoba24. The docs link you sent is our API reference, but our PHP SDK doesn't have those functions yet (to comunicate with our API). So, no, they haven't been completed yet :)

**Comment by kleytonbp** [comment]
Issue solved in PR #195.

**Comment by SOSTheBlack** [comment]
#195
