### ISSUE TITLE
getToken() duplicado em NotificationPreferences

### ISSUE THREAD

**Issue by kleytonbp** [moip/moip-sdk-php#187]
O método getToken está duplicado na classe NotificationPreferences, linhas [89](https://github.com/moip/moip-sdk-php/blob/develop/src/Resource/NotificationPreferences.php#L89-L92) e [119](https://github.com/moip/moip-sdk-php/blob/develop/src/Resource/NotificationPreferences.php#L119-L122).

Com isso o seguinte erro está sendo retornado nos testes: 

> PHP Fatal error:  Cannot redeclare Moip\Resource\NotificationPreferences::getToken() in /Users/kpilon/Desktop/moip-sdk-php/src/Resource/NotificationPreferences.php on line 119

Aparentemente os métodos duplicados retornam o mesmo atributo ($this->data->token), apenas com os comentários diferentes (o primeiro indicando return string e o outro return stdClass).

**Comment by caiogaspar** [comment]
Olá @kleytonbp, obrigado por nos comunicar. Essa issue já está sendo resolvida no #183.
Abs,
Caio Gaspar
