### ISSUE TITLE
Não retorna as informações do customer

### ISSUE THREAD

**Issue by souzadavi** [moip/moip-sdk-php#190]
![screenshot from 2017-10-03 22-11-38](https://user-images.githubusercontent.com/636225/31155885-d85e1e0a-a887-11e7-9224-70944023336b.png)

Não sei se é aqui o local correto, mas não consigo retornar o customer cadastrado, sempre da exceção. porém não mostra o erro, coloquei umas imagens em anexo o ID do customer esta correto, mas ele não retorna, se tento gravar um novo customer com o mesmo ID da erro dizendo q o ID do customer deve ser único.

try {
    $customer_id = 'CUS-Q3BL0CAJ2G33';
    $customer = $moip->customers()->get($customer_id);
    print_r($customer);
} catch (Exception $e) {
    printf($e->__toString());
}
![screenshot from 2017-10-03 22-10-39](https://user-images.githubusercontent.com/636225/31155863-c01d74f8-a887-11e7-87c9-29a6a03095aa.png)

**Comment by kleytonbp** [comment]
Talvez o problema esteja no formato que a API está retornando o erro, quando faço GET em  https://sandbox.moip.com.br/v2/customers/CUS-Q3BL0CAJ2G33, ela está retornando: `{ "error": "resource not found" }`.

Porém na [documentação](https://documentao-moip.readme.io/v2.0/reference#section--error-states-) está indicando que deveria retornar o atributo JSON "errors", com um array dentro. Como esse atributo JSON não está sendo recebido, provavelmente o exception é disparado por causa do HTTP status (404) e o parser de erros da SDK acaba retornando um array vazio por não encontrar o atributo.

**Comment by caiogaspar** [comment]
Olá @souzadavi, tudo bem? 
Certifique-se de que a autenticação que você usa para criar o customer é a mesma para fazer a consulta. Realmente o que o @kleytonbp disse está correto, geralmente isso ocorre quando o customer não existe. Temos trabalhado para melhorar as respostas de erro das SDK's e API's do Moip, para que fique mais claro e fácil de tratar as exceções.
Se o problema persistir, recomendo entrar em contato com os nossos analistas através do integracao@moip.com.br

Abs,
Caio Gaspar

**Comment by souzadavi** [comment]
Estranho o ID existe porq não deixa eu gravar outro customer com o ID q estou passando, da um pau doido!!! vou enviar email para o pessoal da integração, obrigado pela ajuda!

**Comment by souzadavi** [comment]
O erro continua o pessoal da integração não retorna... tem alguém por favor q poderia me ajudar? Obrigado

**Comment by souzadavi** [comment]
acho q descobri aq com a ajuda do pessoal do moip, mesmo definindo o ID do customer o moip cria um aleatorio pra ele, uma pergunta qual seria a melhor forma de vincular um ID do customer do moip com meu usuario dentro do meu sistema? Obrigado pessoal.

**Comment by thiagolima-bm** [comment]
Se vc precisar fazer consulta por ID tem q armazenar no teu sistema.

Abs,

**Comment by souzadavi** [comment]
So mais uma dúvida, a consulta pode ser feita por outro campo??

**Comment by caiogaspar** [comment]
@souzadavi É possível consultar também passando esse seu próprio ID (não o do Moip) como nesse exemplo: https://github.com/moip/moip-sdk-php#consulta-valor-espec%C3%ADfico
