### ISSUE TITLE
Não consigo criar pedido com cliente

### ISSUE THREAD

**Issue by latreta** [moip/moip-sdk-php#194]
Já fiz toda a lógica para consultar cliente já existente ou criar novo
Porém na hora de criar o pedido ele me dá essa exception

```
ErrorException (E_NOTICE)
Undefined property: stdClass::$taxDocument
```
Mas o cliente já tem os dados setados corretamente de acordo com a documentação.

```
$customer->data->taxDocument = new stdClass();
$customer->data->taxDocument->type = $this->getIfSet('type', $response->taxDocument);
$customer->data->taxDocument->number = $this->getIfSet('number', $response->taxDocument);
```

**Comment by caiogaspar** [comment]
@latreta Você consegue passar exatamente o código que está usando para criar o pedido?

**Comment by latreta** [comment]
Exatamente o mesmo código do outro issue.

**Comment by caiogaspar** [comment]
Dúvida respondida no #196.
