### ISSUE TITLE
Undefined property: stdClass::$receivers

### ISSUE THREAD

**Issue by latreta** [moip/moip-sdk-php#196]
mesmo setado os exemplos definidos pela wiki. 
Ele diz que nào existe recebedores setados.

**Comment by caiogaspar** [comment]
@latreta Você consegue passar o código que está usando para adicionar os recebedores?

**Comment by latreta** [comment]
```
try {
      $this->pedido = $this->moip->orders()->setOwnId(uniqid());
      for($index_cart = 0; $index_cart < count($cart);$index_cart++){
        $valor = $cart[$index_cart]['price'] * 100;
        $valor = (int)$valor;
        $this->pedido->addItem($cart[$index_cart]['name'], $cart[$index_cart]['quantity'], 'Descricao', $valor);
      }
      $this->pedido->setShippingAmount(3000)
      ->setAddition(1000)
      ->setDiscount(5000)
      ->addInstallmentCheckoutPreferences([1, 6], 0, 100)
      ->addReceiver('MPA-VB5OGTVPCI52', 'PRIMARY', 30000, NULL, false)
      ->addReceiver('MPA-IFYRB1HBL73Z', 'SECONDARY', 2000, NULL, true)
      ->create();
      print_r($this->pedido);
      } catch (Exception $e) {
        print_r($e->__toString());
      }
```

**Comment by caiogaspar** [comment]
@latreta Os recebedores que você está passando estão recebendo valores fixos: o primário 300,00 e o secundário 20,00, isso deveria estar sendo passado dinamicamente, certo? Notei também que você não está passando o cliente, se for um cliente já cadastrado você deve [consulta-lo](https://github.com/moip/moip-sdk-php#consultando-os-dados-de-um-comprador), do contrário [criar um novo](https://github.com/moip/moip-sdk-php#criando-um-comprador) e passar como parâmetro no método `setCustomer`.

Abs!

**Comment by latreta** [comment]
Irei realizar mais testes, eu testei com o pedido original da wiki e não funcionou, esse já seria a versão para o meu código, eu devo ter excluído mas eu tenho uma variável $this->cliente com o cliente(criado ou consultado) e mesmo assim não pegou, se voltar à ter problemas, entro em contato. Obrigado!
