### ISSUE TITLE
Support to get all attributes returned from Accounts

### ISSUE THREAD

**Issue by caiogaspar** [moip/moip-sdk-php#206]
Currently there aren't methods to get the following attributes returned from Accounts API:
- [ ] login
- [ ] accessToken
- [ ] channelId
- [ ] transparentAccount
- [ ] email
- [ ] identity Document
- [ ] createdAt

You can find the official API documentation for Accounts [here (PT-BR)](https://dev.moip.com.br/reference#contas-moip)!

<hr/>

### Implementation Tips:
The methods should be similar to `getId` from [Account](https://github.com/moip/moip-sdk-php/blob/develop/src/Resource/Account.php). 

**Some of these attributes only are returned from API when an account is created with `transparentAccount` setted as true.**

Don't forget to write good tests.

**Comment by kleytonbp** [comment]
Can i take this issue? :)
About the "_acessToken_" attribute, is not coming from API result, where can i find this value?
And the "identityDocument" is equivalent to "_taxDocument_"? "_identityDocument_" attribute is not coming from API also.

**Comment by caiogaspar** [comment]
Hi @kleytonbp! Thank you so much for being so actively contributing!! We really appreciate it!! But would you mind letting this one for someone else have a try at this one?  :smile:

**Comment by kleytonbp** [comment]
Hey @caiogaspar, sure, no problem! :D

**Comment by MbNakaya** [comment]
Bom dia, Caio!
Beleza?

Posso pegar essa issue?

Abraços,
