### ISSUE TITLE
Erro ao consultar um pagamento

### ISSUE THREAD

**Issue by rdenubila** [moip/moip-sdk-php#207]
Olá! Estou tendo algum problema com o método para consultar um pagamento. Estou utilizando exatamente o mesmo código do exemplo, mudando apenas o id do pagamento, mas ele retorna um erro sem nenhuma explicação.

Segue o código utilizado abaixo:
```
	$payment_id = "PAY-D2I4RJJERNDF";
	echo "Id do Pedido: ".$payment_id."<br>";

	try {
		$payment = $moip->payments()->get($payment_id);
		//print_r($payment);

	} catch (Exception $e) {
		printf($e->__toString());
	}
```

Segue um print do erro retornado:
![Erro](https://i.imgur.com/d7XQcn9.png)

E um print do painel do moip, mostrando que o pagamento foi realizado:
![image](https://i.imgur.com/VE799iH.png)

As demais configurações estão todas corretas, uma vez que eu consegui gerar o pedido e enviar o pagamento corretamente. O problema está só na hora de consultar o pagamento.

Desde já, obrigado pela atenção!

**Comment by caiogaspar** [comment]
Olá @rdenubila, tudo bem?
Então, verifica se as chaves de autenticação que você usou para criar o pagamento são as mesmas que você está usando para tentar consulta-lo.
Se o problema persistir, recomendo que entre em contato com nossos analistas pelo email integracao@moip.com.br.

Abs!
