### ISSUE TITLE
setCreditCardHash retorna erro ValidationException 

### ISSUE THREAD

**Issue by guiliredu** [moip/moip-sdk-php#210]
Ao tentar criar um pagamento com cartão de crédito via hash a lib me retorna um erro de validação:

```php
ValidationException in MoipResource.php line 252:
in MoipResource.php line 252
at MoipResource->httpRequest('/v2/orders/ORD-8XWEG9PWG4TR/payments', 'POST', object(Payment)) in Payment.php line 141
```

Segue o código usado pra gerar o pagamento (basicamente é o código de exemplo):

```php
$payment = $order->payments()
    ->setCreditCardHash($hash, $customer)
    ->setInstallmentCount(3)
    ->setStatementDescriptor('FM - '.$description)
    ->execute();
```

Não consegui entender o que causa esse erro. Este mesmo trecho de código (onde gera o customer e a order) é usado caso a pessoa selecione pagamento por boleto e não dá erro (está em produção até)

**Comment by caiogaspar** [comment]
Olá @guiliredu, tudo bem?

Pra ver exatamente o que está sendo retornado como erro de validação, use nossa [seção de tratamento de exceções](https://github.com/moip/moip-sdk-php#tratamento-de-exce%C3%A7%C3%B5es).

Abs!
