### ISSUE TITLE
Objetos retornados pela API

### ISSUE THREAD

**Issue by thundree** [moip/moip-sdk-php#213]
Tudo bem, pessoal?

Comecei a utlizar a API de vocês ontem (24/10) e hoje, depois de criado um wrapper para utilizar dentro de nossa API, eu noto que os objetos retornados pelo **moip-sdk-php** (ex.: **object:Moip\Resource\Orders**) são um pouco complexos de acessar, tendo muitos itens "private".

Existe algum método, fora o cast **(array)$order** que eu possa utilizar para acessar os dados dentro do objeto retornado?
Olhei a documentação daqui e ela não cita tal função.

Grato,

Richard.

**Comment by caiogaspar** [comment]
Olá @thundree, tudo bem?

Então, hoje não existe nenhum método ou recurso pra acessar os dados diretamente. 
Inclusive esse é um problema que nós já percebemos há algum tempo e estamos planejando resolver futuramente, pensamos em estruturar a SDK para que retorne todos os recursos da API em array, que ficaria muito mais simples para o uso.

Essa SDK foi herdada da comunidade, e quando nós do @moip assumimos, ela já estava completamente estruturada dessa forma. Por enquanto isso ainda está sendo analisado e ainda não temos previsão de quando vai ocorrer, mas com certeza está nos planos!

Abs!
