### ISSUE TITLE
Erro no retorno de um create order

### ISSUE THREAD

**Issue by rafaneri** [moip/moip-sdk-php#217]
O seguinte erro está sendo gerado ao chamar a API de order.

```html
<b>Catchable fatal error</b>:  Argument 1 passed to Moip\Resource\Customer::populate() must be an instance of stdClass, null given, called in D:\Temp\Projects\fastsalon.com.br\public_html\controller\includes\vendor\moip\moip-sdk-php\src\Resource\Orders.php on line 156 and defined in <b>D:\Temp\Projects\fastsalon.com.br\public_html\controller\includes\vendor\moip\moip-sdk-php\src\Resource\Customer.php</b> on line <b>244</b><br />
```

O pedido está sendo criado na plataforma, porém o retorno não está sendo montado. ORD-9MIX7XF4OIIV é um dos pedidos que apresentaram erro.

**Comment by MbNakaya** [comment]
Bom dia @rafaneri !
Tudo bem?

Poderia me enviar o snippet de código que está utilizando e informar o fluxo que está seguindo, por gentileza?

Dessa forma, terei mais evidências para encontrar o motivo do erro que está recebendo.

**Comment by rafaneri** [comment]
@MbNakaya!

Desculpas pela demora, segue o trecho:

``` php
try {
            $customer = $this->getCustomer($idClientMoip);
            $order = $this->moip->orders()->setOwnId(uniqid())
            ->addItem($item, 1, $descricao, get_moip_value($valor))
            ->setShippingAmount(0)
            ->setAddition(0)
            ->setDiscount(get_moip_value($desconto))
            ->setCustomer($customer)
            ->addReceiver($this->bussinessAccount, 'PRIMARY', NULL, 30, true)
            ->addReceiver($idProfissionalMoip, 'SECONDARY', NULL, 70, false)
            ->create();

            return $order;
        } catch (Exceptions\UnexpectedException $uneex) {
            echo json_encode(array("erro" => true, "msg" => "Erro inesperado. ".$uneex->__toString())); exit();
        } catch (Exceptions\UnautorizedException $unaex) {
            echo json_encode(array("erro" => true, "msg" => "Falha ao autenticar")); exit();
        } catch (Exceptions\ValidationException $vex) {
            echo json_encode(array("erro" => true, "msg" => "[".$vex->getStatusCode()."]: ".$vex->__toString())); exit();
        } catch (Exception $e) {
            echo json_encode(array("erro" => true, "msg" => $e->__toString())); exit();
        }
```

**Comment by rafaneri** [comment]
Olá, @bressani!
Então, voltamos a integração, a função que estamos usando é exatamente a função get de customers.

A implementação é a seguinte:

```php
public function getCustomer($id) {
        try {
            $customer = $this->moip->customers()->get($id);
            return $customer;
        } catch (Exceptions\UnexpectedException $uneex) {
            echo json_encode(array("erro" => true, "msg" => "Erro inesperado. ".$uneex->__toString())); exit();
        } catch (Exceptions\UnautorizedException $unaex) {
            echo json_encode(array("erro" => true, "msg" => "Falha ao autenticar")); exit();
        } catch (Exceptions\ValidationException $vex) {
            echo json_encode(array("erro" => true, "msg" => "[".$vex->getStatusCode()."]: ".$vex->__toString())); exit();
        } catch (Exception $e) {
            echo json_encode(array("erro" => true, "msg" => $e->__toString())); exit();
        }
    }

```

E this->moip é:

```php
$this->moip = new Moip(new BasicAuth($this->token, $this->key), Moip::ENDPOINT_SANDBOX);

**Comment by rafaneri** [comment]
Realizei novos testes e agora estamos com o seguinte problema:

The following errors ocurred:fundingInstrument.creditCard.hash: Não foi possível descriptografar o hash do cartão.

Estes são os dados utilizados:

**ordem**: ORD-QUEZ3L09O59B
**cliente**: CUS-N6HE9L5YXIPI
**hash**: pXNMxMfO4sFvkswsI/ZNyL7OPI+/pAICLOcTTFjj1vTxz7ZiLztRkUVN879qKrDO7ZGEGTYg2ewNQYYtCpy7aDkrMd3N5d+ylo7y9DB9GwdgoAWs96l+vnT4DgLsBjrqgspECtG/vgLfivL87f2rlU1Y/iUflC3kDlo+xnewYEEo8TMt1Rh1EFkRzmJCdNTVXR6YmXu+vyCsw17CShIM47MaPUHmPQkCPSurwFDTb87WiIwWVI3NjaS1g3hP9LH

**Comment by rafaneri** [comment]
Estou usando o link da lib acima para fazer a criptografia do cartão.

**Comment by rafaneri** [comment]
Turma,
Tudo funcionando. Era um problema na geração da hash do cartão! 
Pode fechar a issue!

**Comment by bressani** [comment]
Oi, @rafaneri ! Me desculpe pela demora, não vi a notificação de novas mensagens nessa issue...

Deu tudo certo então?

Qualquer coisa nos avise!

Abraços!

**Comment by Rafaelcruzrocha220** [comment]
Boa tarde @rafaneri, Estou tendo o mesmo problema na hora de descriptografar o hash, você pode me informar de que forma conseguiu solucionar este erro ?

> Realizei novos testes e agora estamos com o seguinte problema:
> 
> The following errors ocurred:fundingInstrument.creditCard.hash: Não foi possível descriptografar o hash do cartão.
> 
> Estes são os dados utilizados:
> 
> **ordem**: ORD-QUEZ3L09O59B
> **cliente**: CUS-N6HE9L5YXIPI
> **hash**: pXNMxMfO4sFvkswsI/ZNyL7OPI+/pAICLOcTTFjj1vTxz7ZiLztRkUVN879qKrDO7ZGEGTYg2ewNQYYtCpy7aDkrMd3N5d+ylo7y9DB9GwdgoAWs96l+vnT4DgLsBjrqgspECtG/vgLfivL87f2rlU1Y/iUflC3kDlo+xnewYEEo8TMt1Rh1EFkRzmJCdNTVXR6YmXu+vyCsw17CShIM47MaPUHmPQkCPSurwFDTb87WiIwWVI3NjaS1g3hP9LH
> 
> Aqui a chamada que estamos realizando:
> 
> ```
> try {
>             $order = $this->getOrder($idPedidoMoip);
>             $customer = $this->getCustomer($idClienteMoip);
>             $customer->setFullname($nomeCartao);
>             $payment = $order->payments()
>             ->setCreditCardHash($tokenCartao, $customer)
>             ->setDelayCapture() // criando pré-autorização
>             ->setStatementDescriptor($idAgendamento)
>             ->execute();
>             return $payment;
>         } catch (Exceptions\UnexpectedException $uneex) {
>             echo json_encode(array("erro" => true, "msg" => "Erro inesperado. ".$uneex->__toString())); exit();
>         } catch (Exceptions\UnautorizedException $unaex) {
>             echo json_encode(array("erro" => true, "msg" => "Falha ao autenticar")); exit();
>         } catch (Exceptions\ValidationException $vex) {
>             echo json_encode(array("erro" => true, "msg" => "[".$vex->getStatusCode()."]: ".$vex->__toString())); exit();
>         } catch (Exception $e) {
>             echo json_encode(array("erro" => true, "msg" => $e->__toString())); exit();
>         }
> ```

**Comment by rafaneri** [comment]
@Rafaelcruzrocha220 verifica os dados do app que você está usando e se a public key está com as quebras de linha corretas.

**Comment by Rafaelcruzrocha220** [comment]
@rafaneri O problema ainda persiste, ele estava em funcionamento então descarto que seja a PK, o que você quer dizer quando fala dos dados do app ?

**Comment by Rafaelcruzrocha220** [comment]
@rafaneri Você tem algum contato ou skype para entrarmos em contato, pois estamos com dificuldade e precisamos de um help mesmo.

**Comment by rafaneri** [comment]
@Rafaelcruzrocha220 caramba, o melhor seria você entrar no slack da Wirecard, não sou do time.
