### ISSUE TITLE
Erro Interface 'Requests_Auth' not found in 

### ISSUE THREAD

**Issue by felipecerutti** [moip/moip-sdk-php#223]
Prezados,

Fiz a integração do SDK PHP do MOIP e local não tive nenhum problema, quando fui testar online comecei a ver o seguinte erro. **Interface 'Requests_Auth' not found in** 

Fatal error: Interface 'Requests_Auth' not found in /home/*****/vendor/moip/moip-sdk-php/src/Contracts/Authentication.php on line 10

Já tentei solucionar, coloquei o servidor online com a mesma versão de PHP 7.0, achando ser esse o problema e nada mudou.

Alguém já passou por esse problema?

**Comment by SOSTheBlack** [comment]
A interface `Requests_Auth` é de uma dependência que o package utiliza realizar requisições HTTP.

você já rodou o comando `composer install` para instalar as dependência do SDK do MoIP?

**Comment by somentelucas** [comment]
Oi @felipecerutti, ainda está tendo problemas para instalar a dependência?

Vou fechar essa issue aqui, caso ainda esteja tendo problemas, pode reabrir, ok?

Muito obrigado!
