### ISSUE TITLE
Not able to create customer via API

### ISSUE THREAD

**Issue by rahulmahto** [moip/moip-sdk-php#224]
Notice: Trying to get property of non-object in vendor/rmccue/requests/library/Requests/Session.php on line 240

**Comment by rahulmahto** [comment]
I am using the example code

require 'vendor/autoload.php';

use Moip\Moip;
use Moip\Auth\BasicAuth;

$token = '01010101010101010101010101010101';
$key = 'ABABABABABABABABABABABABABABABABABABABAB';

$moip = new Moip(new BasicAuth($token, $key), Moip::ENDPOINT_SANDBOX);


$customer = $moip->customers()->setOwnId(uniqid())
    ->setFullname('Fulano de Tal')
    ->setEmail('fulano@email.com')
    ->setBirthDate('1988-12-30')
    ->setTaxDocument('22222222222')
    ->setPhone(11, 66778899)
    ->addAddress('BILLING',
        'Rua de teste', 123,
        'Bairro', 'Sao Paulo', 'SP',
        '01234567', 8)
    ->addAddress('SHIPPING',
                'Rua de teste do SHIPPING', 123,
                'Bairro do SHIPPING', 'Sao Paulo', 'SP',
                '01234567', 8)
    ->create();
print_r($customer);

and its throwing error

**Comment by bressani** [comment]
Hello, @rahulmahto ! 
Have you tried this command before running this example code?
`composer require moip/moip-sdk-php`

**Comment by MbNakaya** [comment]
Hello, @rahulmahto!

I'll close this _issue_. But you can reopen it, if you think necessary.

Regards.
