### ISSUE TITLE
Adicionar itens dinamicamente na Ordem de Pedido

### ISSUE THREAD

**Issue by jlessamn** [moip/moip-sdk-php#227]
Caros, bom dia !

Tenho a seguinte situação que vocês já devem ter passado e rapidamente saberão como resolver.

Meus itens do carrinho ficam armazenados no meu DB, onde faço uma consulta no momento da criação do pedido.

Estou utilizando a API com o seguinte código base para criação da ordem:

$order = $moip->orders()->setOwnId("123")
  ->addItem("Item1",1, "Item numero 1", 200)
  ->addItem("Item2",1, "Item numero 2", 400)
  ->addItem("Item3",1, "Item numero 3", 600)
  ->setShippingAmount(10)
  ->setAddition(0)
  ->setDiscount(0)
  ->setCustomerId("CUS-P0OYI1G7UJ65")
  ->addReceiver("MPA-CF9980AAFFD4", "PRIMARY", null, 100, true)
  ->create();

Preciso saber como faço para carregar os itens da minha tabela no pedido dinamicamente, neste exemplo é utilizado o método addItem com um número fixo de itens, preciso saber como adicionar uma quantidade variável de itens.

Obrigado,
Jorge Lessa

**Comment by SOSTheBlack** [comment]
Utilize o foreach no resultado da sua query para add os itens dinamicamente.

```php
$order = $moip->orders()->setOwnId("123")
->setShippingAmount(10)
->setAddition(0)
->setDiscount(0)
->setCustomerId("CUS-P0OYI1G7UJ65")
->addReceiver("MPA-CF9980AAFFD4", "PRIMARY", null, 100, true)

foreach($items_query_results as $items_query_result) {
	$order->addItem($items_query_result->product, $items_query_result->quantity, $items_query_result->detail, $items_query_result->price,);
}

$order->create();
```
