### ISSUE TITLE
Como confirmar um multipagamento usando cartão de crédito 

### ISSUE THREAD

**Issue by latreta** [moip/moip-sdk-php#231]
Eu não estou conseguindo confirmar um pagamento criado através de cartão de crédito usando hash.

Existe alguma forma de confirmar o pagamento que nem o boleto bancário?

**Comment by bressani** [comment]
Olá @latreta !

Você pode dar um get passando o id do payment.

(https://github.com/moip/moip-sdk-php/blob/develop/src/Resource/Payment.php#L153)

Qualquer coisa nos avise 😄 

Abraços!
