### ISSUE TITLE
Como fazer transferência passando somente o id da conta bancária

### ISSUE THREAD

**Issue by leoneparise** [moip/moip-sdk-php#233]
Boa tarde,

Gostaria de saber como faço para fazer uma transferência para uma conta bancária já cadastrada. Não vi também a opção de realizar a transferência a partir da conta moip do cliente.

Att,
Leone Parise.

**Comment by leoneparise** [comment]
Já abri um PR para esse problema: https://github.com/moip/moip-sdk-php/pull/239

**Comment by MbNakaya** [comment]
Boa tarde, @leoneparise!
Tudo bem?

Já iniciamos o _review_ do seu [PR](#239).
Nós agradecemos pela contribuição com o desenvolvimento da SDK. :+1: 

Sobre a opção de transferência entre contas Moip, estamos trabalhando na implementação dessa _feature_ para a SDK e, em breve, será disponibilizada no projeto. :wink: 

Abraços.
