### ISSUE TITLE
Criação de mais de um pagamento por odem

### ISSUE THREAD

**Issue by czmarcos** [moip/moip-sdk-php#241]
Gostaria de saber se é possível criar mais de um pagamento por ordem.

Estou fazendo um loop com boletos bancários com data de vencimento a cada +30 dias, praticamente um parcelamento por boleto bancário.

Para isso, estou aproveitando uma mesma ordem (ORD-XXXXX) e criando vários pagamentos relacionados a ela. Porém, durante este loop a API está me retornando o seguinte erro: "[0] The following errors ocurred:: O pedido já foi pago", e assim acaba emitindo apenas o primeiro pagamento.

Gostaria de saber se é possível fazer isso que estou tentando ou o correto seria criar uma única ordem e utilizá-la para um único pagamento.

Valeu!

**Comment by MbNakaya** [comment]
Boa tarde, @czmarcos!
Tudo bem?

De fato, os pedidos suportam apenas um pagamento. Por isso, não é possível aplicar essa lógica para parcelar o pagamento.

No entanto, você pode realizar um parcelamento utilizando o `"installmentCount"` ou o `"checkoutPreferences"`, através do link de checkout. :smile:
> **Somente pagamentos por cartão de crédito podem ser parcelados.**

Abraços. :+1:

**Comment by czmarcos** [comment]
Valeu @MbNakaya ! No final fiz um loop para criar novas/diferentes ordens/pagamentos e vou incrementando o vencimento dos boletos em +30 dias.
