### ISSUE TITLE
Erro da criação de um pedido

### ISSUE THREAD

**Issue by hereck** [moip/moip-sdk-php#244]
`Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/moedagamer/public_html/vendor/moip/moip-sdk-php/src/Resource/Orders.php on line 158
A PHP Error was encountered
Severity: Parsing Error

Message: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

Filename: Resource/Orders.php

Line Number: 158

Backtrace:`

Sabem o que pode ser?

**Comment by hereck** [comment]
`try {
    $order = $moip->orders()->setOwnId(uniqid())
    ->addItem("bicicleta 1", 1, "sku1", 10000)
    ->addItem("bicicleta 2", 1, "sku2", 11000)
    ->addItem("bicicleta 3", 1, "sku3", 12000)
    ->setShippingAmount(3000)
    ->setAddition(1000)
    ->setDiscount(5000)
    ->setCustomer($customer)
    ->addInstallmentCheckoutPreferences([1, 6], 0, 100)
    ->addReceiver('MPA-VB5OGTVPCI52', 'PRIMARY', 30000, NULL, false)
    ->addReceiver('MPA-IFYRB1HBL73Z', 'SECONDARY', 2000, NULL, true)
    ->create();
} catch (Exception $e) {
    printf`

**Comment by MbNakaya** [comment]
Olá, @hereck!
Tudo bem?

O código acima está correto e funcionando normalmente. Acredito que o erro pode ter ocorrido por conta de uma incompatibilidade de versão do PHP.
> Versão necessária para a SDK: `PHP >= 5.5`

Você também pode atualizar a SDK utilizando o camando `composer require moip/moip-sdk-php`, dentro do diretório do projeto (favor verificar as atualizações, através do [CHANGELOG.md](https://github.com/moip/moip-sdk-php/blob/master/CHANGELOG.md)). :rocket: 

No caso de dúvida ou se o problema persistir, fique à vontade para reabrir essa issue. :smile: 

Abraços.
