### ISSUE TITLE
Erro ao Criar Conta "/accounts"

### ISSUE THREAD

**Issue by lffruhling** [moip/moip-sdk-php#245]
Estou tentando utilizar o seguinte código para criar uma conta

$moip = new Moip(new OAuth($token), Moip::ENDPOINT_SANDBOX);
        $retorno = $moip->accounts()
            ->setEmail($request->email)
            ->setName($request->nome)
            ...
            ->setBusinessSegment(1)
            ->create();

Porém meu único retorno é :

ErrorException (E_WARNING)
Creating default object from empty value

vendor/moip/moip-sdk-php/src/Resource/Account.php -> L. 648

public function setBusinessSegment($segmentId)
    {
        $this->data->businessSegment->id = $segmentId;
        return $this;
    }
Não sei exatamente o porque que o objeto esta vazio se estou forçando a passagem de um número inteiro por paramêntro...

Outro Detalhe que observei. O Moip::ENDPOINT_SANDBOX Não contem o /V2 no final. Deixando a url do sanbox no seguinte formato : 'https://sandbox.moip.com.br' sendo que na documentação deveria ser assim: 'https://sandbox.moip.com.br/v2'

**Comment by MbNakaya** [comment]
Olá, @lffruhling!
Tudo bem?

Bom, verificamos que a utilização do método `setBusinessSegment()` está lançando um _Warning_, não um erro. Mas isso não está afetando o atual funcionamento dessa _feature_, pois as contas estão sendo criadas normalmente e com o `businessSegment.id` esperado.

No entanto, identificamos o motivo que levou ao _Warning_ e já iniciamos a correção. :smile:

Sobre o `ENDPOINT_SANDBOX`, as URLs são construídas corretamente, com o `/v2`. Todos os _endpoints_ da SDK são estendidos ao `MoipResource.php`, que possui a constante `VERSION = 'v2'` e os métodos `generatePath()` e `generateListPath()`, onde o _path_ é gerado com o `/v2`.

Agradecemos pelo seu _feedback_! :rocket:

Abraços. :grin: :+1:
