### ISSUE TITLE
Split de pagamentos apresentando erro ao inverter contas

### ISSUE THREAD

**Issue by diogolanna** [moip/moip-sdk-php#250]
Ao criar um order utilizando o SDK dessa forma o processo ocorre sem problemas:

> $order->addReceiver('xxxxxx', 'PRIMARY', NULL, 100 - $event->marketplaceSplit);
$order->addReceiver($eventOwner->usr_moip, 'SECONDARY', NULL, $event->marketplaceSplit); 

Porém ao inverter as contas:

> $order->addReceiver($eventOwner->usr_moip, 'PRIMARY', NULL, $event->marketplaceSplit, false); 
$order->addReceiver('xxxxxx', 'SECONDARY', NULL, 100 - $event->marketplaceSplit, true); 

 obtenho o erro abaixo:
`"message": "Undefined property: stdClass::$taxDocument",
    "exception": "ErrorException",
    "file": "/var/www/html/wodengageGamesDebug/api/vendor/moip/moip-sdk-php/src/Resource/Customer.php",
    "line": 261,`

Ja verifiquei as contas diretamente via API .

Algumas ideia do porque do erro?

**Comment by MbNakaya** [comment]
Olá, @diogolanna!
Tudo bem?

Você verificou o _customer_ que está sendo utilizado na criação do _order_? Pois o erro não está nas contas dos recebedores e nem no tipo de recebedor que cada uma se encontra (primário ou secundário), o `ErrorException` aponta para a classe `Customer.php`.

Não consegui reproduzir a mensagem de erro. Todos os meus testes passaram.

Recomendo [criar um novo _customer_](https://github.com/moip/moip-sdk-php#criando-um-comprador), certificando-se de que o CPF é passado no método `setTaxDocument()`, e realizar o teste, outra vez.

Se continuar tendo erro assim, reabre a issue com o código da criação dos customers.
