### ISSUE TITLE
Consulta Cliente por TaxDocument ou OwnID

### ISSUE THREAD

**Issue by eversonaraujo** [moip/moip-sdk-php#251]
Olá gostaria de solicitar a opção de buscar o cliente pelo taxDocument ou pelo OwnId na API pois não gostaria de ter que salvar o ID do cliente que pertence ao escopo de vocês no meu banco de dodos, e se a API de vocês já apresenta a possibilidade de cadastrar o meu identificador (setOwnId) nada mais lógico do que me dar a opção de busca-lo com este identificador.

Obrigado!

**Comment by MbNakaya** [comment]
Olá, @eversonaraujo!
Tudo bem?

A implementação desses parâmetros de busca, na SDK-PHP, já está em nosso _roadmap_. Pretendemos lançar essa _feature_ durante os próximos _releases_ da SDK. :smile: 

Agradecemos pelo seu _feedback_! :+1: 

Abraços!
