### ISSUE TITLE
Typo na classe Connect

### ISSUE THREAD

**Issue by Pedr0Rocha** [moip/moip-sdk-php#262]
Acredito ter achado um erro de digitação na função `setScodeAll()` da classe Connect. Pelo contexto o nome provavelmente seria setScopeAll.

https://github.com/moip/moip-sdk-php/blob/c1781cba6e621bd210f459341b1d6c9ff6fb2edb/src/Auth/Connect.php#L171

**Comment by mariodias** [comment]
Olá @Pedr0Rocha como vai?

Analisamos o código e o nome do método está correto, pois se refere ao code gerado através da autorização dos scopes.

#enjoy
