### ISSUE TITLE
Retorno de Status

### ISSUE THREAD

**Issue by mpeota78** [moip/moip-sdk-php#265]
Não consigo pegar o ID_WEBHOOK e o retorno do status

$notification = $moip->notifications()->addEvent('ORDER.*')
            ->addEvent('PAYMENT.AUTHORIZED')
            ->setTarget('http://site.com/retorno')
             ->create();
$status = $moip->webhooks()->get(ID_WEBHOOK);
$status->getStatus(); 

    print_r($status);
exit();

**Comment by mpeota78** [comment]
Nenhum retorno!

**Comment by mpeota78** [comment]
Resolvido com o apoio de Yves Gregorio

**Comment by MbNakaya** [comment]
Boa tarde, @mpeota78!

No atual estado da SDK, não existe um método que permita acessar o atributo de um webhook. No momento, a implementação te permite listar todos os webhooks recebidos e, dessa forma, printar o retorno (pelo `print_r`).

Se achar necessário, pode reabrir a issue ou enviar um novo comentário.
