### ISSUE TITLE
Tratamento dos erros - Retornar em Array ou Json, está vindo apenas como string

### ISSUE THREAD

**Issue by FelipoAntonoff** [moip/moip-sdk-php#266]
Olá, tudo bem?
Poderiam colocar no SDK o quanto antes, tratamento correto dos erros, hoje é usado o `$e->__toString();` e outros métodos, que retornam apenas string dentro do catch, porém não da para trabalharmos com validação correta dessa forma.

Tem na API uma documentação  completa sobre os erros retornados, porém no retorno do SDK vem em string e não array ou json, não dando para fazermos um tratamento correto dos erros.

Segue a parte de erros da documentação [aqui.](https://dev.moip.com.br/v2/reference#erros-1)

Basta retornarem um array ou json no padrão informado na documentação, com o code, path e o message, assim conseguimos trabalhar de forma correta na validação para o cliente final e não retornam uma string estranha para o mesmo.

Conto com a colaboração de vocês.
Atenciosamente, Felipo Antonoff.

**Comment by mbnakaya** [comment]
Olá @FelipoAntonoff 

Nos desculpe pela demora no retorno.

Agradecemos pelo seu feedback e concordo com a necessidade de melhorar o tratamento de erros da SDK, aproveitando melhor os recursos da API. No entanto, essa melhoria não estava em nosso roadmap.

Atualmente, acredito que podemos voltar nossa atenção para esse ponto e melhorar o tratamento, como bem sugerido.

Obrigado pelo feedback!
