### ISSUE TITLE
Criando o pedido para o cliente com o cartão salvo

### ISSUE THREAD

**Issue by souzadavi** [moip/moip-sdk-php#269]
Pessoal excelente essa SDK, mas estou com dificuldade referente a realizar pagamento com o ID do cartão de credito salvo. Isso esta implementado na SDK??

Com base na info: https://dev.moip.com.br/v2.0/reference#criar-pagamento
fundingInstrument.creditCard object
Dados do cartão utilizado no pagamento. Pode ser usado o id de um Cartão previamente salvo, um hash de um cartão criptografado ou a coleção de dados do cartão caso você possua certificação PCI.

Tentei fazer assim:
 $order = $moip->orders()->setOwnId(uniqid())
            ->addItem('bicicleta 1', 1, 'sku1', 10000)
            ->setCustomer(CUS-34543543)
            ->create();
            print_r($order);
        // Creating payment to order
        $payment = $order->payments()
            ->setCreditCardHash(CRC-PQPN6SMNKAD, CUS-34543543)
            ->setInstallmentCount(3)/// PARCELAS
            ->setStatementDescriptor('teste de pag')
            ->execute();

Mas da erro: Dizendo que o setCreditCardHash do cartão de credito tem q ser um objeto e não uma string.

Estava vendo esse manual, 
https://dev.moip.com.br/v2.0/docs/guia-avan%C3%A7ado-1#section--criando-o-pedido-para-o-cliente-com-o-cart-o-salvo-

o SDK tem esse recurso? se não, é possível habilitar a SDK pra esse recurso? Como seria o procedimento para inserir na SDK?

Muito obrigado...

**Comment by mariodias** [comment]
Olá @souzadavi :)

Para criar pagamentos no SDK utilizando o id do cartão, você deverá utilizar o método setCreditCardSaved($creditCardId, $cvc), segue exemplo de utilização:

$payment = $order->payments()->setCreditCardSaved($creditCardId, $cvc)
    ->execute();

#enjoy

**Comment by souzadavi** [comment]
coisa linda, vlw @mariodias funcionou perfeitamente!!!

**Comment by souzadavi** [comment]
@mariodias estou usando o $payment = $order->payments()->setCreditCardSaved($creditCardId, $cvc)
->execute(); porém em outra issue o @mbnakaya disse que tenho que criar um holder, verificando na documentação, ficou ainda mais confuso porque não tem esse método setCreditCardSaved(). Mesmo utilizando esse método preciso definir o holder?

obs.: A "outra issue" mencionado no texto acima: https://github.com/moip/moip-sdk-php/issues/278

No sandbox funciona lindo só q em produção não vai de jeito nenhum, apresenta Código de cancelamento 7.

**Comment by somentelucas** [comment]
E aí @souzadavi, te respondi lá na outra issue, ok?
