### ISSUE TITLE
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/bruno.ribas/clientes/vendor/moip/moip-sdk-php/src/Resource/Orders.php on line 163

### ISSUE THREAD

**Issue by brunoribas68** [moip/moip-sdk-php#270]
Está retornando o erro -  Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/bruno.ribas/clientes/vendor/moip/moip-sdk-php/src/Resource/Orders.php on line 163

o código é:
`<?php
require '../vendor/autoload.php';
require_once 'ConexaoController.php';
use Moip\Moip;
use Moip\Auth\BasicAuth;
$token = 'WUVOYJCHFZVAFTPVVT3IWM5PPR8ZPQSR';
$key = 'TDAGAX5ALWS3WQ7ZWU94FOC5TNVLIYSYSBE7GFNH';
$moip = new Moip(new BasicAuth($token, $key), Moip::ENDPOINT_SANDBOX);
$dataFim = $_POST["dataFim"];
$dataInicio = $_POST["dataInicio"];
$conexao = new Conexao();
$consulta = $conexao->conectaAPI();
$sql = "CALL faturamento_automatico_WebService('".$dataInicio." 00:00:00','".$dataFim." 00:00:00');";

$query = $consulta->query($sql) or die($consulta->errno .' - '. $consulta->error);

while($row = $query->fetch_assoc()) {
  $customer = $moip->customers()->get($row["idMoip"]);
  $order = $moip->orders()->setOwnId($row["cn_id"])
          ->addItem("Grupo BCI",1,"Consultas",intval(substr(str_replace('.','',$row["valor"]), 0, -1)))
          ->setShippingAmount(0)->setAddition(0)->setDiscount(0)
          ->setCustomer($customer)
          ->create();
}
?>`

**Comment by mbnakaya** [comment]
Olá @brunoribas68

Nos desculpe pela demora no retorno.

Executei o código em questão, aplicando os devidos ajustes para que pudesse testa-lo localmente, e obtive sucesso na requisição.

Utilizei o seguinte código adaptado:
```php
<?php

require 'vendor/autoload.php';
// require_once 'ConexaoController.php';

use Moip\Moip;
use Moip\Auth\BasicAuth;

$token = 'WUVOYJCHFZVAFTPVVT3IWM5PPR8ZPQSR';
$key = 'TDAGAX5ALWS3WQ7ZWU94FOC5TNVLIYSYSBE7GFNH';
$moip = new Moip(new BasicAuth($token, $key), Moip::ENDPOINT_SANDBOX);

// $dataFim = $_POST["dataFim"];
// $dataInicio = $_POST["dataInicio"];

// $conexao = new Conexao();

// $consulta = $conexao->conectaAPI();

// $sql = "CALL faturamento_automatico_WebService('".$dataInicio." 00:00:00','".$dataFim." 00:00:00');";

// $query = $consulta->query($sql) or die($consulta->errno .' - '. $consulta->error);

$customer = $moip->customers()->get("CUS-88CKD40F62ET");

$order = $moip->orders()->setOwnId("cn_id_1023012301")
->addItem("Grupo BCI", 1, "Consultas", 10000)
->setShippingAmount(0)->setAddition(0)->setDiscount(0)
->setCustomer($customer)
->create();

print_r($order);
```
Obtive, como resposta da requisição, o seguinte order ID `ORD-ANTK42CUWTYO`.

Acredito que o erro que está recebendo é causado pela incompatibilidade de valores aceitos pela SDK, vindos da sua base de dados. Portanto, peço que verifique se o tipo dos valores passados são aceitos pela SDK.

Fecharei a issue, mas se o problema persistir, fique à vontade para nos contactar novamente.
