### ISSUE TITLE
Como obter o valor da taxa da transação?

### ISSUE THREAD

**Issue by souzadavi** [moip/moip-sdk-php#272]
Na luta pela finalização do script aqui o SDK ajudou demais. Estou com dificuldades em saber como obter o valor da taxa da transação. Gerei o pedido e fiz o pagamento por cartão de crédito, 

$order = $moip->orders()->setOwnId(uniqid())
            ->addItem('bicicleta 1', 1, 'sku1', 10000)
            ->setCustomer($customerMoip)
            ->create();
            $payment = $order->payments()->setCreditCardSaved($moipCC, $moipCVC)
    ->execute();

so que o retorno não tem o valor da taxa dessa transação, alguém sabe como obter o valor da taxa da transação? é possível? ou preciso calcular o custo da transação?

![screenshot from 2018-05-11 12-56-03](https://user-images.githubusercontent.com/636225/39933941-b20f20b0-551a-11e8-8067-610dd5cb8cdb.png)

Obrigadooo

**Comment by mbnakaya** [comment]
Olá @souzadavi 

Ficamos contentes em saber que o SDK foi de grande utilidade. 👍🚀 

No momento, não existe uma API para consultar a taxa de transação, por isso o SDK não retorna esse valor. No entanto, você pode consultar nossa página sobre [tarifas](https://moip.com.br/tarifas/) para maiores informações.

Fique à vontade para nos contactar novamente, se achar necessário.

**Comment by souzadavi** [comment]
Olá @mbnakaya obrigado pelo retorno, o difícil que minhas taxas são super variáveis super complexo de calcular, o moip deveria retornar com o valor das taxas,seria muito mais simples. Mas ai é outro caso, vou ver o q faço muito obrigado novamente pela resposta!

**Comment by souzadavi** [comment]
Bom pessoal primeiramente muito obrigado, acredito que consegui finalizar a primeira versão do script irei enviar para o MOIP avaliar e assim q aprovado pretendo liberar o código fonte do modulo do WHMCS com moip transparente para todos.... Não sei porque pensei que o retorno do callback do moip não viria com a taxa aplicada.... mas ao tratar o retorno do moip consegui visualizar o valor da taxa a notificação PAID vem com todas informações, abaixo deixo um exemplo do retorno de uma notificação do moip, talvez seja útil para alguém.

Esse é uma array q o MOIP envia para ser utilizado no callback do pagamento.
Array
(
    [date] => 
    [env] => 
    [event] => ORDER.PAID
    [resource] => Array
        (
            [order] => Array
                (
                    [_links] => Array
                        (
                            [checkout] => Array
                                (
                                    [payBoleto] => Array
                                        (
                                            [redirectHref] => https://checkout-new-sandbox.moip.com.br?token=6660e458-c130-4sb5-3f92-86c4de5d493a&id=ORD-933KF64QZ4UOS&payment-method=boleto
                                        )

                                    [payCheckout] => Array
                                        (
                                            [redirectHref] => https://checkout-new-sandbox.moip.com.br?token=6660e458-c130-4sb5-3f92-86c4de5d493a&id=ORD-933KF64QZ4UOS&id=ORD-99KR64QZ4UOS
                                        )

                                    [payCreditCard] => Array
                                        (
                                            [redirectHref] => https://checkout-new-sandbox.moip.com.br?token=6660e458-c130-4sb5-3f92-86c4de5d493a&id=ORD-933KF64QZ4UOS&payment-method=credit-card
                                        )

                                    [payOnlineBankDebitItau] => Array
                                        (
                                            [redirectHref] => https://checkout-sandbox.moip.com.br/debit/itau/ORD-933KF64QZ4UOS
                                        )

                                )

                            [self] => Array
                                (
                                    [href] => https://sandbox.moip.com.br/v2/orders/ORD-933KF64QZ4UOS
                                )

                        )

                    [amount] => Array
                        (
                            [currency] => BRL
                            [fees] => 8444
                            [liquid] => 144112
                            [otherReceivers] => 0
                            [paid] => 152556
                            [refunds] => 0
                            [subtotals] => Array
                                (
                                    [addition] => 0
                                    [discount] => 0
                                    [items] => 152556
                                    [shipping] => 0
                                )

                            [total] => 152556
                        )

                    [checkoutPreferences] => Array
                        (
                            [installments] => Array
                                (
                                )

                        )

                    [createdAt] => 2018-05-22T00:06:53.000-03
                    [customer] => Array
                        (
                            [_links] => Array
                                (
                                    [hostedAccount] => Array
                                        (
                                            [redirectHref] => https://hostedaccount-sandbox.moip.com.br?token=558dd07e-cbfc-eed1-99a3-d6sfe9e6e0b5&id=CUS-0IGDFRYPE3UU&mpa=MPA-C40QJENFTO0Y
                                        )

                                    [self] => Array
                                        (
                                            [href] => https://sandbox.moip.com.br/v2/customers/CUS-0IGFSRYPE3UU
                                        )

                                )

                            [birthDate] => 1981-07-08
                            [createdAt] => 2018-05-22T00:06:43.000-03
                            [email] => souzadavi2@gmail.com
                            [fullname] => Davi Souza
                            [fundingInstrument] => Array
                                (
                                    [creditCard] => Array
                                        (
                                            [brand] => VISA
                                            [first6] => 401200
                                            [id] => CRC-N362SDXLW50VV
                                            [last4] => 1112
                                            [store] => 1
                                        )

                                    [method] => CREDIT_CARD
                                )

                            [fundingInstruments] => Array
                                (
                                    [0] => Array
                                        (
                                            [creditCard] => Array
                                                (
                                                    [brand] => VISA
                                                    [first6] => 401200
                                                    [id] => CRC-N3DS33LW50VV
                                                    [last4] => 1112
                                                    [store] => 1
                                                )

                                            [method] => CREDIT_CARD
                                        )

                                )

                            [id] => CUS-0IGZ3fSYPE3UU
                            [moipAccount] => Array
                                (
                                    [id] => MPA-C40QFSN0HO0Y
                                )

                            [ownId] => 5b038941343362
                            [phone] => Array
                                (
                                    [areaCode] => 55
                                    [countryCode] => 55
                                    [number] => nullnull
                                )

                            [taxDocument] => Array
                                (
                                    [number] => 234572539960
                                    [type] => CPF
                                )

                            [updatedAt] => 2018-05-22T00:06:53.000-03
                        )

                    [entries] => Array
                        (
                            [0] => Array
                                (
                                    [_links] => Array
                                        (
                                            [order] => Array
                                                (
                                                    [href] => https://sandbox.moip.com.br/v2/orders/ORD-99KR6FEWZ4UOS
                                                    [title] => ORD-99KR64QZFEOS
                                                )

                                            [payment] => Array
                                                (
                                                    [href] => https://sandbox.moip.com.br/v2/payments/PAY-FB7TNVFSNFV
                                                    [title] => PAY-FB7TNFSGYNFV
                                                )

                                            [self] => Array
                                                (
                                                    [href] => https://sandbox.moip.com.br/v2/entries/ENT-PZNFSDGERCU6
                                                )

                                        )

                                    [amount] => Array
                                        (
                                            [currency] => BRL
                                            [fee] => 8444
                                            [liquid] => 144112
                                            [total] => 152556
                                        )

                                    [createdAt] => 2018-05-21T21:06:55.000-03
                                    [description] => Cartao de credito - Pedido PAY-FB7TNFSFGYNFV
                                    [event] => PAY-FB7TFSFDGYNFV
                                    [id] => ENT-PZNGGDFSFRCU6
                                    [occurrence] => Array
                                        (
                                            [in] => 1
                                            [to] => 1
                                        )

                                    [operation] => CREDIT
                                    [scheduledFor] => 2018-06-04T21:06:54.000-03
                                    [status] => SCHEDULED
                                    [updatedAt] => 2018-05-21T21:06:55.000-03
                                )

                        )

                    [escrows] => Array
                        (
                        )

                    [events] => Array
                        (
                            [0] => Array
                                (
                                    [createdAt] => 2018-05-22T00:06:54.936-03
                                    [description] => 
                                    [type] => ORDER.PAID
                                )

                            [1] => Array
                                (
                                    [createdAt] => 2018-05-22T00:06:53.000-03
                                    [description] => 
                                    [type] => ORDER.CREATED
                                )

                        )

                    [id] => ORD-99KR6FSDDF4UOS
                    [items] => Array
                        (
                            [0] => Array
                                (
                                    [category] => OTHER_CATEGORIES
                                    [detail] => 8
                                    [price] => 152556
                                    [product] => Link DEV - Fatura #8
                                    [quantity] => 1
                                )

                        )

                    [ownId] => 8:5b038S3348de9
                    [payments] => Array
                        (
                            [0] => Array
                                (
                                    [_links] => Array
                                        (
                                            [order] => Array
                                                (
                                                    [href] => https://sandbox.moip.com.br/v2/orders/ORD-99KR6FSF4Z4UOS
                                                    [title] => ORD-99FSR44QZ4UOS
                                                )

                                            [self] => Array
                                                (
                                                    [href] => https://sandbox.moip.com.br/v2/payments/PAY-FB7FE$TEGYNFV
                                                )

                                        )

                                    [acquirerDetails] => Array
                                        (
                                            [authorizationNumber] => T12996
                                            [taxDocument] => Array
                                                (
                                                    [number] => 01027058000191
                                                    [type] => CNPJ
                                                )

                                        )

                                    [amount] => Array
                                        (
                                            [currency] => BRL
                                            [fees] => 8444
                                            [gross] => 152556
                                            [liquid] => 144112
                                            [refunds] => 0
                                            [total] => 152556
                                        )

                                    [createdAt] => 2018-05-22T00:06:54.000-03
                                    [delayCapture] => 
                                    [events] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [createdAt] => 2018-05-22T00:06:54.936-03
                                                    [type] => PAYMENT.AUTHORIZED
                                                )

                                            [1] => Array
                                                (
                                                    [createdAt] => 2018-05-22T00:06:54.000-03
                                                    [type] => PAYMENT.CREATED
                                                )

                                            [2] => Array
                                                (
                                                    [createdAt] => 2018-05-22T00:06:54.000-03
                                                    [type] => PAYMENT.IN_ANALYSIS
                                                )

                                        )

                                    [fees] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [amount] => 8444
                                                    [type] => TRANSACTION
                                                )

                                        )

                                    [fundingInstrument] => Array
                                        (
                                            [creditCard] => Array
                                                (
                                                    [brand] => VISA
                                                    [first6] => 401200
                                                    [holder] => Array
                                                        (
                                                            [birthDate] => 1981-07-08
                                                            [birthdate] => 1981-07-08
                                                            [fullname] => Davi Souza
                                                            [taxDocument] => Array
                                                                (
                                                                    [number] => 23434325364360
                                                                    [type] => CPF
                                                                )

                                                        )

                                                    [id] => CRC-N362MSFSF50VV
                                                    [last4] => 1112
                                                    [store] => 1
                                                )

                                            [method] => CREDIT_CARD
                                        )

                                    [id] => PAY-FB7TSFSFGYNFV
                                    [installmentCount] => 1
                                    [receivers] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [amount] => Array
                                                        (
                                                            [currency] => BRL
                                                            [fees] => 8444
                                                            [refunds] => 0
                                                            [total] => 152556
                                                        )

                                                    [feePayor] => 1
                                                    [moipAccount] => Array
                                                        (
                                                            [fullname] => Davi Silva de Souza
                                                            [id] => MPA-C40QSFSF0HO0Y
                                                            [login] => souzadavi
                                                        )

                                                    [type] => PRIMARY
                                                )

                                        )

                                    [status] => AUTHORIZED
                                    [updatedAt] => 2018-05-22T00:06:54.936-03
                                )

                        )

                    [platform] => V2
                    [receivers] => Array
                        (
                            [0] => Array
                                (
                                    [amount] => Array
                                        (
                                            [currency] => BRL
                                            [fees] => 8444
                                            [refunds] => 0
                                            [total] => 152556
                                        )

                                    [feePayor] => 1
                                    [moipAccount] => Array
                                        (
                                            [fullname] => Davi Silva de Souza
                                            [id] => MPA-C40QJEN0HO0Y
                                            [login] => souzadavi
                                        )

                                    [type] => PRIMARY
                                )

                        )

                    [refunds] => Array
                        (
                        )

                    [status] => PAID
                    [updatedAt] => 2018-05-22T00:06:54.936-03
                )

        )
)

esse é apenas o retorno do     [event] => ORDER.PAID, o MOIP envia vários eventos, é preciso ir no manual da API do MOIP para mais informações.


Obrigadooooo....

**Comment by lua-net** [comment]
> Olá @souzadavi
> 
> Ficamos contentes em saber que o SDK foi de grande utilidade. +1rocket
> 
> No momento, não existe uma API para consultar a taxa de transação, por isso o SDK não retorna esse valor. No entanto, você pode consultar nossa página sobre [tarifas](https://moip.com.br/tarifas/) para maiores informações.
> 
> Fique à vontade para nos contactar novamente, se achar necessário.

Esta é a pior justificativa possível, a SDK existe exatamente para facilitar a vida dos desenvolvedores se se integrarem com a MOIP, se é para ser desta forma então não vale utilizar a SDK, pois não tem condições de metada do código ficar na SDK nativa da moip e a outra metade em uma SDK que temos que construir para utilizar as API's da MOIP!
