### ISSUE TITLE
Retorno do Criar Pedido faltando dados do Customer

### ISSUE THREAD

**Issue by gilbertoss** [moip/moip-sdk-php#274]
De acordo com a documentação https://dev.moip.com.br/v2.0/reference#criar-pedido-2 o retorno da chamada de criação de pedidos deveria conter o taxDocument do cliente, mas atualmente não recebo esse retorno.
Documentação:
![image](https://user-images.githubusercontent.com/6839320/40174895-d4307dba-59ac-11e8-9615-4d11ca2222ba.png)

Retorno:
![image](https://user-images.githubusercontent.com/6839320/40174957-07cf2ab8-59ad-11e8-8ac8-19ff88ea5fde.png)

Isso está causando erro na linha 261 da Classe Custumer.php:
![image](https://user-images.githubusercontent.com/6839320/40175033-44f747cc-59ad-11e8-869f-34193bce2370.png)

**Comment by mariodias** [comment]
Issue sendo tratada via zendesk*

**Comment by mbnakaya** [comment]
Recebi informações de que o problema foi tratado e resolvido via chat, pelo time de **Integração**. Por esse motivo, fecharei a issue.

Fique à vontade para reabri-la, se achar necessário.
