### ISSUE TITLE
Pagamento em analise

### ISSUE THREAD

**Issue by souzadavi** [moip/moip-sdk-php#275]
Olá muito obrigado pelas respostas, estou com uma dúvida, todo o pagamento por cartão de crédito fica em "IN_ANALYSIS", deve ser feito alguma coisa para esse pagamento ser aprovado?

é possível o pagamento ser aprovado na hora do envio do payment?
$payment = $order->payments()->setCreditCardSaved()->execute();

Após esse procedimento devo fazer algo para liberar e autorizar o pagamento?
porque no manual esta escrito que ele irá para: PRE_AUTHORIZED
https://dev.moip.com.br/v2.0/reference#eventos

Pré-autorizado: esse status indica a reserva do valor do pagamento no cartão do cliente. Após a pré-autorização é possível fazer a captura em até 5 dias. Passado esse período o Moip cancelará a transação automaticamente.

Mas quando eu entro em minha conta no sandbox ele já esta como pago. Fiquei com dúvida sobre o procedimento. Após enviar o payment, preciso fazer algo mais para receber?

Muitíssimo obrigado!

**Comment by souzadavi** [comment]
acho q a resposta esta aqui https://dev.moip.com.br/docs/webhook

**Comment by mariodias** [comment]
Ola @souzadavi 

Caso você crie um pagamento no Moip, definindo o parâmetro "delayCapture" como "true", será necessário você enviar um POST ao Moip para autorizar o mesmo, a autorização só pode ser solicitada caso o pagamento esteja com o status "PAYMENT.PRE_AUTHORIZED". para pagamentos em que não seja setada a pré autorização, a autorização ou o cancelamento ocorrem de forma automática.

Segue referência: https://github.com/moip/moip-sdk-php#capturar-pagamento-pr%C3%A9-autorizado

:)

**Comment by souzadavi** [comment]
Não defini o parametro "delayCapture". O pagamento provavelmente deve ser aprovado de imediato, mas mesmo assim criei um callback para receber os webhooks através da notificação. O estranho q não estou conseguindo printar os dados recebidos do MOIP, é como se viesse vázio....

O sandbox do moip tem dado alguns erros, agora fiquei na dúvida aonde estou errando...
![screenshot from 2018-05-21 20-36-22](https://user-images.githubusercontent.com/636225/40334860-ca1d8970-5d36-11e8-8e26-4f297f309597.png)

as notificação estão sendo geradas mas não consigo obter os valores. fiquei com algumas dúvidas básicas de como receber esses dados e utilizar esse recurso dentro do meu arquivo php.
![screenshot from 2018-05-21 20-38-21](https://user-images.githubusercontent.com/636225/40334933-477f658c-5d37-11e8-8bf2-aa58283c964f.png)

// Pega o RAW data da requisição
$json = file_get_contents('php://input');
// Converte os dados recebidos
$response = json_decode($json, true);


Muito obrigado pela atenção....

**Comment by mariodias** [comment]
Olá @souzadavi 

por gentileza, confirme o seu login Moip para que eu possa analisar as falhas.

**Comment by souzadavi** [comment]
Olá @mariodias obrigado pelo retorno, meu email no sandbox é contato@linknacional.com.br mas eu consegui encontrar a solução com ajuda ai de vcs.... acabei de solicitar a homologação tentei colocar em produção o modulo mas da erro de conexão na produção acho q tem q aguardar a homologação..... é a primeira versão do modulo mas já esta 100% funcional agora é ir testando e aperfeiçoando, muito obrigado pela ajuda ai!!!! vou deixar o repositório aq do modulo whmcs de checkout transparente do cartão de crédito com o moip.... https://bitbucket.org/linknacional/moip_credit_cart_whmcs

**Comment by souzadavi** [comment]
Opa o link acima do bitbucket esta errado...  o correto é https://bitbucket.org/linknacional/moip_credit_card_whmcs
