### ISSUE TITLE
Verifica se o usuário já tem uma conta MOIP

### ISSUE THREAD

**Issue by souzadavi** [moip/moip-sdk-php#277]
Pessoal esse metodo busca o CPF do usuário em todo o MOIP ou apenas em minha conta dentro do MOIP? Se o usuário possuir uma conta moip é possível obter os dados dele apenas com o CPF tipo o ID CUS-987908RWERW98098?

Verifica se usuário já possui conta Moip
// retorna verdadeiro se já possui e falso caso não possuir conta Moip
$moip->accounts()->checkAccountExists(CPF);

Obrigado

**Comment by mbnakaya** [comment]
Olá @souzadavi 

O método `checkAccountExists($cpf)` faz uma busca em todo o sistema para verificar se existe alguma conta Moip cadastrada com este CPF.

Não é possível obter dados de uma conta Moip somente pelo CPF, é necessário possuir o ID desse conta e as devidas permissões do usuário. Já o ID da conta Moip, que possui o formato `MPA-XXXXXXX`, é retornado na resposta da requisição de criação de contas. Enquanto o ID mencionado, com o formato `CUS-XXXXXXX`, pertence ao cliente de uma conta Moip.

Para entender um pouco mais sobre as contas Moip, o fluxo do Marketplace e o que são as permissões do usuário, recomendo conferir a nossa [documentação](https://dev.moip.com.br/v2.0/docs/app-1).

Se achar necessário, fique à vontade para comentar e/ou reabrir esta issue. 👍
