### ISSUE TITLE
URLs dos ambientes

### ISSUE THREAD

**Issue by andersonkoester** [moip/moip-sdk-php#3]
Este repositório está setado para a utilização das URLs da documentação V1 (test.moip.com.br).

Mesmo modficando para a URL atual não há como executar as chamadas.

**Comment by vagnerfiuza** [comment]
@andersonkoester a URL test.moip.com.br se refere as novas API do Moip.
A URL referente a v1 é (desenvolvedor.moip.com.br/sandbox), esse SDK possui abstração apenas para as APIs v2, por isso a nova URL (test.moip.com.br).

Descreva o erro que você está recebendo ao tentar chamar as novas APIs.
Lembrando que ela ainda é restrita como BETA, e é necessário que você possua um convite para poder realizar requests na nova API.

**Comment by andersonkoester** [comment]
@vagnerfiuza, não está conectando a URL test.moip.com.br, por isso pensei que estava apontando para a api antiga.

Não consigo retornar nem o PING para este endpoint.

**Comment by andersonkoester** [comment]
@vagnerfiuza, 
Vi agora apenas esta parte do teu comentário "Lembrando que ela ainda é restrita como BETA, e é necessário que você possua um convite para poder realizar requests na nova API.". Não tenho este convite... vou pegar a API antiga. Valeu!

**Comment by vagnerfiuza** [comment]
@andersonkoester Nos envie um e-mail para dev@moip.com.br contando um pouco mais sobre o seu projeto, dessa forma podemos avaliar as features necessárias e te conceder acesso caso possamos te atender. ;)
