### ISSUE TITLE
Assinaturas

### ISSUE THREAD

**Issue by gabrielkoerich** [moip/moip-sdk-php#33]
Bom dia!

Pelo que eu vi, o package ainda não aceita a criação de planos e assinaturas

Isso está planejado?

**Comment by vagnerfiuza** [comment]
Bom dia @gabrielkoerich realmente não contempla a API de Assinaturas.
Está planejado sim mas a principio não nesse SDK e sim um especifico para o modelo de Assinaturas, ainda sem previsão.

**Comment by SOSTheBlack** [comment]
Olá @gabrielkoerich.
Estamos desenvolvendo os testes unitários para este sdk, assim que esse desenvolvimento for finalizado, será desenvolvido a parte de assinaturas.
Mas como o @vagnerfiuza disse, sem previsão.

**Comment by gabrielkoerich** [comment]
Opa, tranquilo!

Estamos desenvolvendo uma plataforma de automação de marketing e CRM, ainda temos umas coisas para fazer e provavelmente no fim do mês que vem iremos começar a integrar pagamentos por assinatura.

A minha idea era integrar o moip da mesma forma que o Taylor (usamos laravel) integrou o stripe no cashier. Vocês acham que isso é possível com a API v2?

**Comment by SOSTheBlack** [comment]
Olá, @gabrielkoerich 

Cara lógico que é possível, ajudaria também se você contribuísse com o package para Laravel.
https://github.com/artesaos/moip

**Comment by NandoKstroNet** [comment]
Pessoal, desculpem ressuscitar a issue. Temos o sdk para assinaturas? Ou este que estamos já comtempla?

Abs.

**Comment by marcus-campos** [comment]
Estou com a mesma dúvida
