### ISSUE TITLE
Colocar ano de nascimento no cartão de crédito gera Bad Request

### ISSUE THREAD

**Issue by menezes-** [moip/moip-sdk-php#40]
No pull request #38 foi inserido suporte para objetos DateTime, porém eu esqueci de colocar a conversão de DateTime para string na função `setCreditCardHolder` dentro de `Resource\Payment` e `setCreditCard` dentro de `Resource\Customer` .

**Comment by menezes-** [comment]
Vou corrigir no próximo pull request que eu fizer

**Comment by SOSTheBlack** [comment]
https://github.com/moip/moip-sdk-php/issues/43
