### ISSUE TITLE
Adicionar o método getLinks() a classe MoipResource

### ISSUE THREAD

**Issue by menezes-** [moip/moip-sdk-php#58]
A API do moip segue o padrão HATEOAS<sup>[1](http://dev.moip.com.br/referencia-api/?json#abordagem-restful)</sup> e portanto todos os resources retornados pela API contém o campo `_links` porém, na SDK PHP, apenas a classe `Orders` implementa a função necessária para pegar os links.  Isso começa a complicar um pouco a vida quando se executa um pagamento por boleto, pois não é possível pegar o link do boleto a partir da classe `Payment`

**Comment by SOSTheBlack** [comment]
Resolvido no PR #59

**Comment by guiliredu** [comment]
Caiu fora esse método? Como pego os links de uma Order?
