### ISSUE TITLE
UnautorizedException in MoipResource.php line 162:

### ISSUE THREAD

**Issue by devfelipereis** [moip/moip-sdk-php#62]
[401] Erro de Autenticação. confirme se sua autenticação pode realizar a ação desejada e se está usando o ambiente correto, lembre-se que as chaves de produção e de sandbox são distintas.

Eu simplesmente instalei este pacote na minha aplicação em Laravel e ao tentar fazer um teste recebi este erro. Segui somente os passos da documentação, preciso fazer mais alguma coisa?

Criei uma conta na sandbox e troquei as chaves para testar o primeiro exemplo "Criando um comprador".

Obrigado!

**Comment by SOSTheBlack** [comment]
Para Laravel utilize esse package.
https://github.com/artesaos/moip

Se persistir avisa!

**Comment by devfelipereis** [comment]
Acabei de mudar para este pacote que sugeriu e acabei recebendo o mesmo erro. Alguma ideia?

**Comment by SOSTheBlack** [comment]
Vou fazer um teste essa noite com as minhas credenciais e com as credenciais default do Moip.
Te dou um feedback após isso!

**Comment by devfelipereis** [comment]
Ok. Já revisei e testei e continuo com o mesmo erro. Vou aguardar pelos seus resultados. Obrigado!

**Comment by carlos3duardo** [comment]
Puts, cara. mesmo problema, aqui.
Estou batendo cabeça com isso desde ontem.

**Comment by SOSTheBlack** [comment]
Desculpa mas não tive tempo de fazer os testes ontem.

Acabei de fazer um com o package sem utilizar o Laravel.

composer.json: http://laravel.io/bin/QN3qm
index.php: http://laravel.io/bin/6LoEE#12
json da new order: http://laravel.io/bin/Jx5zy

Obs. Estou utilizando as próprias credenciais de teste do moip.

Irei fazer um teste agora utilizando Laravel e dou um feedback para vocês

**Comment by SOSTheBlack** [comment]
Instalei o Laravel e adicionei o package

Segue os exemplos

composer.json: http://laravel.io/bin/VPm2P
app.php: http://laravel.io/bin/LkaBO
.env: http://laravel.io/bin/wJ4Ge
routes.php: http://laravel.io/bin/qQNkJ

Podem me informar exatamente como vocês estão tentando fazer os teste para eu tentar simular o erro aqui?

**Comment by carlos3duardo** [comment]
Eu estava utilizando a package moip-sdk-php.
Vou mudar para a artesaos/moip e retorno.

**Comment by SOSTheBlack** [comment]
@carlos3duardo eu testei com o sdk e funcionou tbm
O package utiliza tbm o SDK, porem tem o facilitador `facade` do laravel e algumas configs que se utiliza no `.env`.

**Comment by devfelipereis** [comment]
O meu está funcionando. Quase esqueci de comentar aqui.. depois de vários testes em sucesso, entrei em contato com o Moip e eles pediram meu email de login do sandbox e minutos depois já estava funcionando Oo. Fica a dica!

**Comment by SOSTheBlack** [comment]
@devfelipereis Para utilizar a API v2, precisa pedir autorização mesmo!
Irei colocar essa informação no readme

@carlos3duardo algum feedback?

**Comment by devfelipereis** [comment]
Sim, mas acontece que no meu não funcionava em nenhuma. Agora funciona nas duas. Não sei o que pode ser.

**Comment by carlos3duardo** [comment]
Puxa... Achei que com o e-mail de convite era o suficiente.
Vou entrar em contato para ver se tenho o mesmo resultado.
Volto assim que tiver novidades.

**Comment by carlos3duardo** [comment]
Tive um feedback do suporte. Parece que o problema era o mesmo do amigo Felipe.
Não dá mais erro de Autenticação. Deu erro de ValidationException, mas isso eu vejo depois.
Obrigado pelo suporte.

**Comment by SOSTheBlack** [comment]
Blz.

Qualquer coisa tamo ai!

**Comment by guiliredu** [comment]
> @devfelipereis Para utilizar a API v2, precisa pedir autorização mesmo!
Irei colocar essa informação no readme

ainda precisa pedir permissão?
