### ISSUE TITLE
Erro 401 - Erro de Autenticação. 

### ISSUE THREAD

**Issue by jersobh** [moip/moip-sdk-php#63]
Estou recebendo erro 401 no retorno. Funciona perfeitamente em homologação. Minha conta é do tipo "negócio" e alterei o token e chave. No entanto continuo recebendo erro de autenticação. Meu código está como na documentação e funciona perfeitamente em sandbox.

**Comment by SOSTheBlack** [comment]
Entra em contato com o suporte de desenvolvedores do moip, e avisa que vc quer utilizar a API v2.

Por padrão as contas de sandbox estão habilitadas apenas para API v1

 

Atenciosamente,

Jean C. Garcia – Engenheiro de Software

+55 16 9-9280-8021

contato@jeancesargarcia.com.br

 

De: Jefferson de Andrade Santos <notifications@github.com>
Responder para: moip/moip-sdk-php <reply@reply.github.com>
Data: sábado, 27 de agosto de 2016 00:32
Para: moip/moip-sdk-php <moip-sdk-php@noreply.github.com>
Assunto: [moip/moip-sdk-php] Erro 401 - Erro de Autenticação. (#63)

 

Estou recebendo erro 401 no retorno. Funciona perfeitamente em homologação. Minha conta é do tipo "negócio" e alterei o token e chave. No entanto continuo recebendo erro de autenticação. Meu código está como na documentação e funciona perfeitamente em sandbox.

**Comment by SOSTheBlack** [comment]
Chamado fechado por falta de interação
