### ISSUE TITLE
Identificador único de cliente

### ISSUE THREAD

**Issue by valentim-guilherme** [moip/moip-sdk-php#64]
Boa tarde meus caros, minha duvida roda entorno do identificador único do cliente controlado pela Moip (ex: CUS-QMC9OV0GFMZG). Primeiramente gostaria de saber se este ID é imutável ou se sofre alguma alteração quando o cliente tem seus dados atualizados. Pelo que pude perceber este ID pode ser alterado caso alguma alteração nas informações do cliente aconteça, se isso é verdade como posso manter o ID deste cliente atualizado no meu sistema ? Existe alguma forma de consultar o cliente através do ownId ?

O porque da pergunta é que durante o processo de alteração de algumas informações do cliente o ID da moip é atualizado internamente e ao tentar recuperar este cliente posteriormente me deparo com um 404 no endpoint https://sandbox.moip.com.br/v2/customers/ID-MOIP pelo fato do meu ID não ser mais o mesmo para o cliente.

**Comment by SOSTheBlack** [comment]
Olá @valentim-guilherme, bom dia!
Tudo bem com você?

Essa sua dúvida é uma questão referente a regrada de negócio interna da CNova, ou seja, não compete sdk do MoIP definir esse tipo de regra que você pos em pauta!

Peço por favor que entre em cato via chat com o Moip e levante essa dúvida, e se possível, poste a mesma aqui para nós.

Eu sou desenvolvedor do SDK, mas estarei colocando em cópia nesse chamado o @vagnerfiuza que possivelmente pode sanar sua dúvida!

Abraços

**Comment by valentim-guilherme** [comment]
Obrigado pelo retorno meu caro, já enviei uma dúvida para os principais canais da Moip a alguns dias e não obtive retorno. Assim que resolver o problema postarei aqui a solução. Estou aguardando o contato do vagnerfiuza...

**Comment by valentim-guilherme** [comment]
Bom apenas para registro e futuro auxilio a algum interessado segue a resolução do problema:

Basicamente no sistema integrado com a Moip um cliente poderia ter tanto pagamentos recorrentes quanto não recorrentes. Porém até a data atual a Moip não compartilha os recursos da V1 (assinaturas) com a V2 (pagamento n recorrente). E isso faz com que quem queira ter os dois recursos disponíveis tenha que criar um mesmo usuário através das duas integrações. E é ai que o problema vai se manifestar. Embora a V1 não compartilhe os recursos com a V2, ao registrar uma assinatura ou atualiza-la o sistema interno da Moip atualiza o ID do usuário na V2 ao relaciona-lo via ownId com a V1. Sendo assim para evitar que o seu sistema perca a referência do usuário para a V2 basta ao criar o usuário não informar o ownId igual ao id do usuário na V1. Isso ira solucionar o problema porém infelizmente a cada nova assinatura (para um mesmo usuário) seu registro será duplicado.

Segundo o suporte da Moip este problema será solucionado quando a V2 for integrada com o recurso de assinaturas, enquanto isso a solução é trabalhar com registros duplicados.

**Comment by SOSTheBlack** [comment]
@valentim-guilherme Obrigado pelo feedback!
