### ISSUE TITLE
Multiorder

### ISSUE THREAD

**Issue by raffaalves** [moip/moip-sdk-php#66]
Estou tentando efetuar o pagamento de uma multi order mas retorna erro 400, mas estou utilizando igual a o exemplo do Moip.

$multipayments = $this->moip->multiorders()->get('MOR-8H8VSF36G5HT')->multipayments();
$multipayments->setBoleto('2016-09-30', 'https://logo-uri.com', array('Primeira linha se instrução', 'Segunda linha se instrução', 'Terceira linha se instrução')) ->execute();

erro 

-statusCode: 400
  -errors: []
  #message: ""
  #code: 0
  #file: "/home/vagrant/Code/troc/vendor/moip/moip-sdk-php/src/Resource/MoipResource.php"
  #line: 167

O Suporte deles não ajuda, seria um erro do Moip?

**Comment by SOSTheBlack** [comment]
Olá @raffaalves , o package faz apenas o meio de campo, não tempo confirmar se isso é erro API.
Mas você pode pegar json que está sendo enviar e fazer a request via postman.
Compare tbm o json gerado com o que tem na documentação da API.

Nos reporte aqui o resultado

**Comment by paulocraftsys** [comment]
@SOSTheBlack estou com o mesmo problema. O que eu preciso é pegar os status CANCELLED no webhooks e disponibilizar para o cliente uma nova forma de pagamento, ou seja, a mesma multiorder, mas gerando um novo pagamento. Então, se eu hoje pego método: $moip->Multiorders()->get("MOR-931H57W54J25")->multipayments() ele dá o erro abaixo:

<p>Type: Moip\Exceptions\ValidationException</p>
<p>Message: (null)</p>
<p>Filename: /storage/a/11/45/dayshopping1/public_html/_homologacao/vendor/moip/moip-sdk-php/src/Resource
/MoipResource.php</p>
<p>Line Number: 166</p>

o que será que estou fazendo de errado?

**Comment by SOSTheBlack** [comment]
Foi lançado a Versão v1.2, ve se os problema persiste!
