### ISSUE TITLE
Não é possível pegar o status do Pagamento?

### ISSUE THREAD

**Issue by lucassena** [moip/moip-sdk-php#68]
O atributo `status` na classe `Moip\Resource\Payment`, está como protected. Há alguma maneira de recuperar este atributo?

**Comment by SOSTheBlack** [comment]
Olá @lucassena,
No momento em que faz o execute não é possível hoje obter o status do payment.
Porém é possível obter o seu id através do método `getId()`, E através desse id do pagamento você pode fazer uma requisição no pagamento através do método `get()` do payment.

Outra alternativa seria criar um método get para obter o status payment assim que o mesmo é criado, ficaríamos felizes se você implementasse esse método e nos mandasse um PR.

Abraços

**Comment by lucassena** [comment]
Obrigado @SOSTheBlack, vou criar um PR então pra isso! Valeu!
