### ISSUE TITLE
Split de pagamento

### ISSUE THREAD

**Issue by czmarcos** [moip/moip-sdk-php#74]
A api possui endpoint para realizar split de pagamento? Há algum exemplo de como faz a requisição na api? Não encontrei na documentação. grato

**Comment by rodrigogodinho** [comment]
Bom dia czmarcos, existe split de pagamento sim. Ao criar o objeto da classe Order(pedido) existe o método addReceiver onde você define quem serão os recebedores primário e secundários e quanto cada um receberá. Abaixo está o exemplo de como instanciar um objeto Order com split de pagamento:
$order = $moip->orders()->setOwnId('Aqui você coloca o id do pedido em seu sistema')
            ->addItem('Produto', $quantidade, 'Detalhe', $preco)
            ->setCustomer($customer)
            ->addReceiver('id da conta moip do receiver primário', Orders::RECEIVER_TYPE_PRIMARY, 
                $valorPagoReceiverPrimario)
            ->addReceiver('id da conta moip do receiver secundário', Orders::RECEIVER_TYPE_SECONDARY, $valorPagoReceiverSecundario)
            ->create(); 

Espero que este exemplo te ajude czmarcos.

**Comment by czmarcos** [comment]
Ótimo! Valeu @rodrigogodinho!
