### ISSUE TITLE
Link para documentação oficial não funciona

### ISSUE THREAD

**Issue by marciodojr** [moip/moip-sdk-php#79]
O link para documentação oficial informado no arquivo [README.md](https://github.com/moip/moip-sdk-php/blob/master/README.md) não funciona. Poderiam, por favor, corrigir?

[Documentação oficial](https://moip.com.br/referencia-api/)

**Comment by SOSTheBlack** [comment]
Olá @marciodojr, boa tarde!
Tudo bem com você?

Fique a vontade para mandar um pull request com a correção, ficaríamos grato!

Abraços.

**Comment by marciodojr** [comment]
@SOSTheBlack, boa tarde!
se a documentação oficial for a descrição da api da moip https://documentao-moip.readme.io/v2.0/reference, posso mandar o pull request sem problemas. No entanto, achei que poderia haver alguma documentação referente a este repositório gerada via apigen ou phpdocumentor.

**Comment by SOSTheBlack** [comment]
@marciodojr no futuro próximo, por enquanto, é esse link que vc comentou mesmo!
