### ISSUE TITLE
Parcelamento

### ISSUE THREAD

**Issue by rodolfosnery** [moip/moip-sdk-php#92]
Ola, sobre o parcelamento addParcel, não consigo realizar, preciso de ajuda.

Desde Já Obrigado!
Rodolfo Nery

**Comment by SOSTheBlack** [comment]
Olá @rodolfosnery,

Pode me mandar o script na qual vc está tentar fazer a parcela, e qual erro está retornando pf.

**Comment by SOSTheBlack** [comment]
Issue fechado por falta de interação
