### ISSUE TITLE
Contas transparentes

### ISSUE THREAD

**Issue by marciodojr** [moip/moip-sdk-php#93]
Boa tarde, notei que a parte de gestão de contas moip ainda não foi implementada. Seria possível vocês alterarem a visibilidade dos atributos `$moipAuthentication`, `$endpoint` e `$session` na classe `Moip\Moip` de **private** para **protected** para facilitar a implementação de outros itens da API, via herança, mas continuando a utilizar este repositório como base?

**Comment by SOSTheBlack** [comment]
@marciodojr essa parte está em fase de desenvolvimento ainda, fique a vontade para mandar um pull request.
Em questão dos atributos, eles são privados por medidas de segurança

**Comment by SOSTheBlack** [comment]
Caso queira ajudar a deixar o package 100% e testavel me manda um e-mail.

**Comment by marciodojr** [comment]
@SOSTheBlack mandei email para você. Estou à disposição para contribuir com o que for possível.
