### ISSUE TITLE
Add account(vendedores)?

### ISSUE THREAD

**Issue by romereza** [moip/moip-sdk-php#96]
Olá boa tarde,

Estou querendo fazer um pagamento Split, pelo que entendi para criar um vendedor pelo SDK seria o mesmo que criar um Account, mas ai surgiu algumas dúvidas:

- Posso criar uma conta via SandBox, pois estou seguindo as orientações do módulo e está dando "[401] Erro de Autenticação.";
     
[captura de tela 2017-04-07 as 14 54 22](https://cloud.githubusercontent.com/assets/22554489/24813326/fad1e2bc-1ba3-11e7-9912-f67b92e61c5f.png)

- Se já existir um usuário cadastro com este e-mail vai existir algum problema? Se existir problema como faço para recuperar o Id deste usuário;

- Caso não exista nenhum usuário para o email informado e um pagamento for gerado para o mesmo, ao cliente criar e/ou acessar a conta pela primeira vez este crédito já aparece para ele?

Obrigado.

**Comment by SOSTheBlack** [comment]
Posso criar uma conta via SandBox, pois estou seguindo as orientações do módulo e está dando
R: Você não pode ter dois clientes com o mesmo email.

Se já existir um usuário cadastro com este e-mail vai existir algum problema? Se existir problema como faço para recuperar o Id deste usuário;
R De uma olhada nas sources do package
https://github.com/moip/moip-sdk-php/blob/master/src/Resource/Customer.php#L118

Caso não exista nenhum usuário para o email informado e um pagamento for gerado para o mesmo, ao cliente criar e/ou acessar a conta pela primeira vez este crédito já aparece para ele?
R: Entre em contato com o suporte de desenvolvedores do MoIP e detalhe melhor a sua pergunta.
