### ISSUE TITLE
Ajustes no SDK

### ISSUE THREAD

**Issue by romereza** [moip/moip-sdk-php#98]
Olá,

Precisei fazer alguns ajustes no SDK para funcionar bem no meu sistema, segue abaixo alguns prints e as explicações para conhecimentos de vocês.

1 - Caso eu tentasse criar uma conta de um usuário (account) já existente o SDK me retornava apenas a mensagem erro, não me retornava o campo "additionalInfo" onde possui o id do mesmo:
![captura de tela 2017-04-11 as 18 06 26](https://cloud.githubusercontent.com/assets/22554489/24930920/a63dfcea-1ee1-11e7-9590-3d9f6db0f616.png)

2 - Retornar o Id de um respectivo usuário (account):
![captura de tela 2017-04-11 as 18 07 23](https://cloud.githubusercontent.com/assets/22554489/24930992/ea62afb0-1ee1-11e7-8f14-dcae14955f59.png)

3 - Erro ao setar o valor de um receiver:
![captura de tela 2017-04-11 as 18 10 36](https://cloud.githubusercontent.com/assets/22554489/24931076/3f6be31e-1ee2-11e7-8c20-1d00d1805efc.png)

**Comment by SOSTheBlack** [comment]
@romereza de um pr por favor

**Comment by romereza** [comment]
@SOSTheBlack o que seria pr?

**Comment by SOSTheBlack** [comment]
@romereza Pull Request, por meio dele o seu código estará disponível a todos

**Comment by romereza** [comment]
@SOSTheBlack suspeitei mas gerou a dúvida :)

Mas subo em que ramo? Crio uma branche novo?

**Comment by SOSTheBlack** [comment]
Pesquise em como contribuir com projetos no github.
Basicamente,
De um fork no repositorio
Clone o seu fork
De os commits necessários
de um Pull Request

**Comment by SOSTheBlack** [comment]
@romereza pode subir no master, por enquanto
