### ISSUE TITLE
Cancelar / Reembolso ?

### ISSUE THREAD

**Issue by romereza** [moip/moip-sdk-php#99]
Como fazemos um reembolso e/ou cancelamento de um pedido? Vi que existe a classe Refund mas não entendi direito como funciona :(

Obrigado.

**Comment by SOSTheBlack** [comment]
A documetação do SDK está sendo desenvolvida, acredito que em duas semanas estará pronta.
Existe alguns ajustes que será feito nessa classe.

**Comment by romereza** [comment]
Olá @SOSTheBlack sabes me dizer se existe alguma novidade sobre o manual e/ou sobre como realizar o cancelamento/reembolso pelo sdk?

Obrigado.
